### ISSUE TITLE
Add support for "step" property

### ISSUE THREAD

**Issue by anaximander** [jeanregisser/react-native-slider#16]
This is not a drop-in replacement for SliderIOS.  SliderIOS supports the "step" property, which allows you to define the allowable values generated by the slider (in between your min and max).  See https://facebook.github.io/react-native/docs/sliderios.html#step.  I would love to use this component if support was added for the "step" property.

**Comment by vitalets** [comment]
+1 for step property!

**Comment by williambout** [comment]
:+1:

**Comment by jcsjohnson** [comment]
agreed

**Comment by prashanthv** [comment]
+1

**Comment by oillamp** [comment]
+1

**Comment by faceyspacey** [comment]
ideally, the step allows you to configure different step values at different ranges, i.e:

```
step: [
   {start: 0, increment: 20},
   {start: 500, increment: 50},
   {start: 1000, increment: 100},
]
```

since, this is pure JS, we have a lot of options when it comes to customizability. I need this for a project, so I'd be willing to build this. I'm just looking at this package for the first time as an alternative to SliderIOS--anyone have any tips where to start in order to implement this? 

And of course, I'd built it so if you supply an int instead of an array, it will use that as the "increment" throughout the entire range of the slider. If anyone has different ideas for the API, let me know. 

One challenging part is how exactly does it slide? Basically, it snaps to the total # of steps. And the distance between each step is an equal percentage of the whole width of the slider, regardless if you're going from 0 to 20 or or 500 to 100. That's basically the "interesting" part about what this solution is trying to solve. I.e. it allows you to have a money slider from 0 - $20,000, where you can actually toggle from 0 to $10 to $20 without it being insanely sensitive. That's the overall product goal trying to be solved.

**Comment by alexHlebnikov** [comment]
+1

**Comment by vitalets** [comment]
use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) guys..

**Comment by rreusser** [comment]
[Here's the code](https://github.com/facebook/react-native/blob/4cb775286cfc40219bb0b3666b663213f8cd140c/React/Views/RCTSliderManager.m#L35-L48) that implements it in `SliderIOS`:

```objective-c
value =
  MAX(sender.minimumValue,
    MIN(sender.maximumValue,
      sender.minimumValue + round((sender.value - sender.minimumValue) / sender.step) * sender.step
    )
  );
```

So should be pretty trivial to carry this over into JS.

**Comment by rreusser** [comment]
Ping @anaximander and any other interested parties. I made the following changes in a branch in my repo. You can use it with

```
"react-native-slider": "git@github.com:rreusser/react-native-slider.git#rr-prs"
```

It has the following changes from `jeanregisser/master`:

- allows `step` (#25)
- removed `componentWillReceiveProps` so that value is not controlled (#24)
- Merge disabled option PR (#9)
- Merge thumb position callback PR (#8)

**Comment by jeanregisser** [comment]
I've just published a new release on NPM with @rreusser's `step` prop addition!
Thank you for you contribution. :+1:
