### ISSUE TITLE
Consider transpiling npm package to ES5

### ISSUE THREAD

**Issue by necolas** [jeanregisser/react-native-slider#22]
I found that it's impractical to use this package for web apps because it uses ES6/7 features and doesn't transpile to ES5 before publishing to npm. It's common for web apps to skip transpiling their `node_modules` dependencies.

**Comment by rreusser** [comment]
@necolas — what is the right approach for this, generally speaking? I've done it the crappy way before where both the original and transpiled code are committed and then there's no single source of truth.

The alternatives seem to be either:
- Write only in ES5. This seems weird since there's no great reason modules should lose out on ES6/7.
- Post install transpiling? Or some other hook so that the code is transpiled but only the ES6/7 is committed. This seems maybe best but I'm not 100% sure the correct/best approach.

I'm glad to submit a PR, just not totally sure I know the correct solution.

**Comment by rreusser** [comment]
Answered my own question, I think: https://github.com/sindresorhus/ava/issues/184#issuecomment-155713014

Short answer: it's just a bad idea.

**Comment by jeanregisser** [comment]
Wondering about the use case for this.
@necolas is it to use this component within a shared code base between a react native and react app?
What do other components do to handle that?

**Comment by necolas** [comment]
This situation seems to be an accident of how React Native provides a built-in packager that transpiles installed node_modules. That's led to people publishing packages to npm that require transpilation before they can be used in most js environments. Web projects tend to transpile modules in a prepublish step, so developers do not pass installed node_modules through a transpiler. So when I tried to install this in a web project using React Native for Web, it didn't work out of the box. To see an example of the prepublish conversion to ES5, have a look at reactjs/redux or necolas/react-native-web.

**Comment by rreusser** [comment]
Ah, okay. `prepublish`.

Example: https://github.com/reactjs/redux/blob/master/package.json#L29-L30
Docs: https://docs.npmjs.com/misc/scripts

So it compiles and that ends up on npm even if not committed to the repo (unless I'm mistaken). That's helpful. Thanks, @necolas!

**Comment by rreusser** [comment]
See #29. It sounds like whether to lean on the react native packager to handle ES6/7 is debatable, but hopefully—correct me if I'm mistaken—this is at least the correct way to transpile on publishing.

**Comment by jeanregisser** [comment]
I just published 0.5.3 to NPM with @rreusser changes.
@necolas could you let us know if it works as expected with the transpiled version?

**Comment by jeanregisser** [comment]
Closing this. Please reopen if it doesn't work as expected.
Thanks.
